[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2021"
description = "{{description}}"
authors = [ "{{authors}}" ]

[profile.dev.package.'*']
opt-level = 3

[dependencies]
macroquad = "0.3.25"
